<?php

/**
* @file
* Adds a block showing NASA's Astronomy Photo of the Day
* created by Joshua Alexander
*/

/**
 * Implements hook_block_info().
 */
function apod_block_info() {
	$blocks['apod'] = array(
		// The name that will appear in the block list.
		'info' => t('Astronomy Picture of the Day'),
		// Default setting.
		'cache' => DRUPAL_CACHE_PER_ROLE,
	);
	return $blocks;
}

/**
 * Implements hook_menu().
 */
function apod_menu() {
  $items = array();

  $items['admin/config/apod'] = array(
    'title' => 'Astronomy Picture of the Day',
    'description' => 'Configuration for APOD module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('apod_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback: APOD settings
 *
 * @see apod_menu()
 */
function apod_form($form, &$form_state) {
  $form['apod_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter API Key'),
    '#default_value' => variable_get('apod_api_key', 'NNKOjkoul8n1CH18TWA9gwngW1s1SmjESPjNoUFo'),
    '#size' => 60,
    '#maxlength' => 60,
    '#description' => t('The NASA API key. CLEAR CACHE AFTER CHANGING! If one is needed, you can request one ') .
		l(t('here.'), 'https://api.nasa.gov/index.html#apply-for-an-api-key',
		array('attributes' => array('title' => 'Get NASA API key link'))),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Custom content function.
 *
 * @return
 *   A result of the picture of the day API call.
 */
function apod_contents() {
		ini_set("allow_url_fopen", 1);
		$api_key = variable_get('apod_api_key', 'NNKOjkoul8n1CH18TWA9gwngW1s1SmjESPjNoUFo');
		$url = "https://api.nasa.gov/planetary/apod?api_key=" . $api_key;

		try {
    		$json = file_get_contents($url);
			$data = json_decode($json, true);
		} catch (Exception $ex) {
    		echo 'Failed to reach NASA APOD API: ' . $ex . $api_key;
		}
		return $data;
}

/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function apod_block_view($delta = '') {
	switch ($delta) {
		case 'apod':
			$block['subject'] = t('Astronomy Photo of the Day');
			if (user_access('access content')) {
				$markup = '';
				// Use contents function to make API call and recieve json.
				$result = apod_contents();

				if (is_array($result)) {
					switch ($result['media_type']) {
						case 'image':
							$markup = theme('html_tag', array(
								'element' => array(
									'#tag' => 'div',
									'#attributes' => array(
										'class' => 'apod',),
									'#value' => theme('html_tag', array(
										'element' => array(
											'#tag' => 'h2',
											'#attributes' => array(
												'class' => 'apod-title',),
											'#value' => $result['title']))) . 
										theme('image', array(
											'path' => $result['hdurl'],
											'alt' => $result['title'],
											'title' => $result['title'],
											'width' => '80%',
											'height' => '80%',
											'attributes' => array('class' => 'apod-img'))) . 
										'<p>Image Credit: ' . (isset($result['copyright']) ? $result['copyright'] : 'Other') . '<br>Date: ' .
										$result['date'] . '</p><p>' . $result['explanation'] . '</p>')));
							break;
						case 'video':
							module_load_include('module', 'Iframe');
							$markup = theme('html_tag', array(
								'element' => array(
									'#tag' => 'div',
									'#attributes' => array(
										'class' => 'apod',),
									'#value' =>
										iframe_iframe($result['title'], $result['url'],
											array('title' => $result['title'], 'width' => '80%', 'height' => '300px')) .
										'<p>Video Credit: ' . $result['copyright'] . '<br>Date: ' . 
										$result['date'] . '</p><p>' . $result['explanation'] . '</p>')));
							break;
					}	
				} else {
					$markup = '<p>Failed to reach NASA APOD API. ' .'<br>Check API Key!</p>';
				}
				$block['content'] = $markup;
			}
		return $block;
	}

}

?>